### ISSUE TITLE
SpriteSheetAnimation does not work with rectangular subimages (width is different from height)

### ISSUE THREAD

**Issue by landochan** [IrvKalb/pygwidgets#4]
I noticed the issue in pygwidgets/pygwidgets.py on line 3195, 3196
`            x = col * height`
`            y = row * width`
I think it should be changed to this
`            x = col * width`
`            y = row * height`

**Comment by IrvKalb** [comment]
Hi Lando,

Thank you very much for writing.

It turns out that you are the second person to tell me about this bug within a week!  The bug has been there for probably four years.  I had noticed it because the images that I was working with in my sprite sheets were square, so the width and the height were the same.

The fix that you supplied is exactly correct.  I have made the change in my code and uploaded a 1.0.4 version of pygwidgets to my GitHub repository.  (Although I have not yet published it to PyPI for download.)

I am very close to shipping a new 1.1 version of pygwidgets with a few additional classes, including an AnimationCollection and a SpriteSheetAnimationCollection that work like my ImageCollection.  That is, these allow you to specify a number of different animations and switch between them easily.  Coming soon ...

Again, thanks for letting me know.  I hope that you are enjoying the book.

Irv
________________________________
From: Lando Chan ***@***.***>
Sent: Monday, February 13, 2023 6:12 PM
To: IrvKalb/pygwidgets ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [IrvKalb/pygwidgets] SpriteSheetAnimation does not work with rectangular subimages (width is different from height) (Issue #4)


I noticed the issue in pygwidgets/pygwidgets.py on line 3195, 3196
x = col * height
y = row * width
I think it should be changed to this
x = col * width
y = row * height

**Comment by landochan** [comment]
Thank you for the fix
